# Generated by Django 4.0.6 on 2022-08-14 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reqeust_type', models.CharField(blank=True, choices=[('Maintenance', 'Maintenance'), ('Lost/Found', 'Lost/Found')], default='Maintenance', max_length=20, null=True)),
                ('request_name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('request_state', models.CharField(blank=True, choices=[('Open', 'Open'), ('Close', 'Close'), ('Work_In_Progress', 'Work_In_Progress')], default='Open', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('photo', models.ImageField(upload_to='')),
                ('claimed', models.BooleanField(default=False)),
                ('claimed_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
