# Generated by Django 4.0.6 on 2022-09-04 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0006_report_returned_alter_report_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='item_returned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_item_returned_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
