# Generated by Django 4.0.6 on 2023-05-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_report_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
    ]
