# Generated by Django 4.0.6 on 2022-08-14 20:20

from django.db import migrations, models

import datetime
class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='expiry',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now().isoformat()),
            preserve_default=False,
        ),
    ]
