# Generated by Django 4.0.6 on 2022-08-15 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_alter_verificationcode_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 21, 47, 16, 721051)),
        ),
    ]
