# Generated by Django 4.0.6 on 2023-05-30 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0057_alter_verificationcode_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='expiry',
        ),
    ]
