# Generated by Django 4.0.6 on 2022-08-19 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergency',
            options={'verbose_name_plural': 'Emergencies'},
        ),
    ]
