# Generated by Django 4.0.6 on 2022-08-19 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emergency', '0002_alter_emergency_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergency',
            old_name='numbers',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='emergency',
            name='emergency_type',
            field=models.CharField(blank=True, choices=[('Hospital/Clinic', 'Hospital/Clinic'), ('Fire Services', 'Fire Services'), ('Ambulance Services', 'Ambulance Services'), ('Rescue Services', 'Rescue Services')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emergency',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
