# Generated by Django 4.0.6 on 2022-08-24 15:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_messagemodel_uploadedfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='file',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='message', to='messaging.uploadedfile', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
    ]
