# Generated by Django 4.0.6 on 2022-08-24 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_remove_messagemodel_file_messagemodel_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='conversation',
        ),
    ]
