# Generated by Django 4.0.6 on 2022-08-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_conversationsmodel_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
    ]
