# Generated by Django 4.0.6 on 2022-08-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='single_iamge',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
