# Generated by Django 4.0.6 on 2022-08-14 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_property_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='owner',
            new_name='user',
        ),
    ]
