# Generated by Django 4.0.6 on 2022-08-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_rename_owner_property_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='order',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
