# Generated by Django 4.0.6 on 2022-08-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_alter_propertyimage_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
