# Generated by Django 4.0.6 on 2022-08-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_alter_propertyimage_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='room_images',
            new_name='images',
        ),
    ]
