# Generated by Django 4.0.6 on 2022-08-19 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_rename_room_images_room_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
    ]
