# Generated by Django 4.0.6 on 2022-08-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0018_alter_propertyapplication_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyapplication',
            name='documents',
            field=models.ManyToManyField(blank=True, null=True, to='property.documents'),
        ),
    ]
