# Generated by Django 4.0.6 on 2022-08-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_alter_propertyapplication_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyapplication',
            name='documents',
            field=models.ManyToManyField(blank=True, to='property.documents'),
        ),
    ]
