# Generated by Django 4.0.6 on 2022-11-09 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0021_alter_documents_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInRoomSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CheckOutRoomSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='RoomOccupancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('check_in_images', models.ManyToManyField(blank=True, related_name='check_in_iamges', through='property.CheckInRoomSection', to='property.section')),
                ('check_out_images', models.ManyToManyField(blank=True, related_name='check_out_images', through='property.CheckOutRoomSection', to='property.section')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff', models.PositiveIntegerField(blank=True, null=True)),
                ('check_in_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_section', to='property.section')),
                ('check_out_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_out_section', to='property.section')),
                ('diff_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.image')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
                ('room_occupancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.roomoccupancy')),
            ],
        ),
        migrations.AddField(
            model_name='checkoutroomsection',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.section'),
        ),
        migrations.AddField(
            model_name='checkoutroomsection',
            name='room_occupancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.roomoccupancy'),
        ),
        migrations.AddField(
            model_name='checkinroomsection',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.section'),
        ),
        migrations.AddField(
            model_name='checkinroomsection',
            name='room_occupancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.roomoccupancy'),
        ),
    ]
