# Generated by Django 4.0.6 on 2022-11-11 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_checkinroomsection_checkoutroomsection_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discrepancy',
            name='check_in_image',
        ),
        migrations.RemoveField(
            model_name='discrepancy',
            name='check_out_image',
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='discrepancy_at',
            field=models.CharField(choices=[('check-in', 'check-in'), ('check-out', 'check-out')], default='check-out', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='expected_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expected_image', to='property.image'),
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='uploaded_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.section'),
        ),
        migrations.AddField(
            model_name='roomoccupancy',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.room'),
        ),
        migrations.AlterField(
            model_name='discrepancy',
            name='diff_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difference_image', to='property.image'),
        ),
        migrations.AlterField(
            model_name='roomoccupancy',
            name='check_in_images',
            field=models.ManyToManyField(blank=True, related_name='check_in_images', through='property.CheckInRoomSection', to='property.section'),
        ),
    ]
