# Generated by Django 4.0.6 on 2022-12-29 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_inspection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inspection',
            new_name='InspectionSchedule',
        ),
    ]
