# Generated by Django 4.0.6 on 2022-12-29 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0026_rename_inspection_inspectionschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionschedule',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='property.property'),
        ),
    ]
