# Generated by Django 4.0.6 on 2022-12-29 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_alter_inspectionschedule_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionschedule',
            name='last_triggered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inspectionschedule',
            name='period',
            field=models.SmallIntegerField(verbose_name='inspection interval with day'),
        ),
    ]
