# Generated by Django 4.0.6 on 2022-12-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0028_alter_inspectionschedule_last_triggered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionschedule',
            name='period',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='inspection interval with day'),
        ),
    ]
