# Generated by Django 4.0.6 on 2022-12-29 18:49

from django.db import migrations
from property.models import Property,InspectionSchedule

def create_property_inspection_scheduals(apps, schema):
    for property in Property.objects.all():
        InspectionSchedule.objects.get_or_create(
            property=property
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0029_alter_inspectionschedule_period'),
    ]

    operations = [
        migrations.RunPython(
            create_property_inspection_scheduals
        )
    ]
