# Generated by Django 4.0.6 on 2022-08-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrequest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mrequest',
            old_name='reqeust_type',
            new_name='request_type',
        ),
        migrations.AlterField(
            model_name='mrequest',
            name='request_state',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Close', 'Close'), ('Work_In_Progress', 'Work_In_Progress'), ('Pending', 'Pending')], default='Pending', max_length=20, null=True),
        ),
    ]
