# Generated by Django 4.0.6 on 2022-08-22 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_documents_propertyapplication'),
        ('mrequest', '0002_rename_reqeust_type_mrequest_request_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mrequest',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_request', to='property.property'),
        ),
        migrations.AlterField(
            model_name='mrequest',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mrequest',
            name='request_name',
            field=models.CharField(max_length=200),
        ),
    ]
